### ISSUE TITLE
Starting truckersmp-cli using proton-tkg

### ISSUE THREAD

**Issue by bimokn97** [truckersmp-cli/truckersmp-cli#182]
i cant start using proton tkg, the logs shows  :

``
truckersmp-cli --account bimokn97 --prefixdir '/home/bimo/Game/Steam/steamapps/compatdata/227300' --gamedir '/home/bimo/Game/Steam/steamapps/common/Euro Truck Simulator 2' --protondir /home/bimo/.steam/root/compatibilitytools.d/proton_tkg_6.8.r15.gf308782d --proton --activate-native-d3dcompiler-47 --enable-d3d11 --ets2 --start
Traceback (most recent call last):
  File "/home/bimo/.local/bin/truckersmp-cli", line 19, in <module>
    main()
  File "/home/bimo/.local/lib/python3.9/site-packages/truckersmp_cli/main.py", line 153, in main
    start_game()
  File "/home/bimo/.local/lib/python3.9/site-packages/truckersmp_cli/main.py", line 210, in start_with_proton
    activate_native_d3dcompiler_47(prefix, wine)
  File "/home/bimo/.local/lib/python3.9/site-packages/truckersmp_cli/utils.py", line 68, in activate_native_d3dcompiler_47
    subproc.call(
  File "/usr/lib64/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/bimo/.steam/root/compatibilitytools.d/proton_tkg_6.8.r15.gf308782d/dist/bin/wine'
``

But this can fixed by changing 

`` wine = os.path.join(Args.protondir, "dist/bin/wine")`` to  `` wine = os.path.join(Args.protondir, "files/bin/wine")``

on main.py
maybe this need an switcher, but i cant find the code for that.

also maybe you can add env WINEFSYNC=1 by default.

Thanks

**Comment by bimokn97** [comment]
Finally, Thanks a lot
