### ISSUE TITLE
Python IndexError when starting truckersmp-cli in singleplayer mode

### ISSUE THREAD

**Issue by kallestrop** [truckersmp-cli/truckersmp-cli#213]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
Suddenly truckersmp-cli stopped working with `IndexError: list index out of range` when starting in singleplayer.

## Expected behavior
Running Euro Truck Simulator 2 in singleplayer mode with start option `start ets2`.

## Command
~~~
truckersmp-cli --enable-d3d11 --proton --activate-native-d3dcompiler-47 -vv start ets2
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/user/.local/share/truckersmp-cli/TruckersMP
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/user/.local/share/truckersmp-cli/Proton
** INFO **  Steam Runtime directory: /home/user/.local/share/truckersmp-cli/SteamRuntime
** DEBUG **  Starting game with Proton
** DEBUG **  Steam is running
** INFO **  Steam installation directory: /home/user/.local/share/Steam
** DEBUG **  Creating directory /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix if it doesn't exist
** INFO **  Proton version is (major=6, minor=3)
** INFO **  Using Steam Runtime container
Traceback (most recent call last):
  File "/home/user/.local/bin/truckersmp-cli", line 19, in <module>
    main()
  File "/home/user/.local/lib/python3.9/site-packages/truckersmp_cli/main.py", line 182, in main
    start_game()
  File "/home/user/.local/lib/python3.9/site-packages/truckersmp_cli/main.py", line 233, in start_with_proton
    shared_paths += get_steam_library_dirs(steamdir)
  File "/home/user/.local/lib/python3.9/site-packages/truckersmp_cli/utils.py", line 398, in get_steam_library_dirs
    steam_libraries.append(elements[3])
IndexError: list index out of range

~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)

</details>

## Information
 - OS: Debian Bullseye
 - Proton or Wine version: `Proton 6.3`, `Steam Runtime Version 0.20210630.17`
 - truckersmp-cli version: `0.6.2`

## Additional context
Starting in multiplayer with `truckersmp-cli --enable-d3d11 --proton --activate-native-d3dcompiler-47  -vv start ets2mp` is working.

**Comment by Lucki** [comment]
I guess you're in the steam beta, Valve rolled out the new library format yesterday.

Some more info: https://github.com/truckersmp-cli/truckersmp-cli/pull/183#discussion_r663304302

**Comment by kallestrop** [comment]
Yes, i am in Steam beta branch and there was an update this morning. 

I checked also my secondary Linux installation which is Linux Mint 20.2. It's the same Steam beta branch but here truckersmp-cli starts singleplayer session without errors. 

The only difference i see between my Debian installation and Linux Mint installation is a different Steam installation path.

In Debian it's `~/.local/share/Steam` while in Linux Mint it's `~/.steam/debian-installation`

Terminal output when starting in Linux Mint `truckersmp-cli --enable-d3d11 --proton --activate-native-d3dcompiler-47 -vv start ets2`

## Terminal output
<details><summary>Collapsed log</summary>

~~~
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/user/.local/share/truckersmp-cli/TruckersMP
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/user/.local/share/truckersmp-cli/Proton
** INFO **  Steam Runtime directory: /home/user/.local/share/truckersmp-cli/SteamRuntime
** DEBUG **  Starting game with Proton
** DEBUG **  Steam is running
** INFO **  Steam installation directory: /home/user/.steam/debian-installation
** DEBUG **  Creating directory /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix if it doesn't exist
** INFO **  Proton version is (major=6, minor=3)
** INFO **  Using Steam Runtime container
** DEBUG **  Shared paths: ['/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/user/.local/share/truckersmp-cli/Proton', '/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix', '/home/user/.steam/debian-installation', '/home/user/.local/lib/python3.8/site-packages/truckersmp_cli']
** DEBUG **  d3dcompiler_47.dll is present, MD5 is OK.
** DEBUG **  Copying d3dcompiler_47.dll into /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/windows/system32
** DEBUG **  Adding DLL override setting for eurotrucks2.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Der Vorgang wurde erfolgreich abgeschlossen
** INFO **  Running Steam Runtime helper:
  SteamAppId=227300
  SteamGameId=227300
  LD_PRELOAD=/home/user/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so
  PROTON_NO_D3D11=0
  PROTON_USE_WINED3D=0
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/debian-installation
  STEAM_COMPAT_DATA_PATH=/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  python3
    /home/user/.local/share/truckersmp-cli/Proton/proton
    run
    /home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data/bin/win_x64/eurotrucks2.exe
    -nointro
    -64bit
Executables: None
Game Arguments: ['python3', '/home/user/.local/share/truckersmp-cli/Proton/proton', 'run', '/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data/bin/win_x64/eurotrucks2.exe', '-nointro', '-64bit']
Proton output:
ERROR: ld.so: object '/home/user/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/user/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970862824 [API loaded no]
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Fossilize INFO: Overriding serialization path: "/home/user/.steam/debian-installation/steamapps/shadercache/227300/fozpipelinesv5/steamapprun_pipeline_cache".
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Fossilize INFO: Overriding serialization path: "/home/user/.steam/debian-installation/steamapps/shadercache/227300/fozpipelinesv5/steamapprun_pipeline_cache".
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970862824 [API loaded no]
pid 4644 != 4643, skipping destruction (fork without exec?)
~~~
</details>

**Comment by Lucki** [comment]
You can compare your `<steam installation>/steamapps/libraryfolders.vdf`. Your Mint installation might not have additional LibraryFolders configured or isn't converted to the new format yet.
