### ISSUE TITLE
[crash] Args.prefixdir isn't set to its default value if not using a config file

### ISSUE THREAD

**Issue by aearil** [truckersmp-cli/truckersmp-cli#260]
Since commit 9ffe4b7, the launcher crashes while trying to launch the game with the following traceback:

~~~
Traceback (most recent call last):
  File "/home/***/dev/truckersmp-cli/./truckersmp-cli", line 19, in <module>
    main()
  File "/home/***/dev/truckersmp-cli/truckersmp_cli/main.py", line 142, in main
    update_mod()
  File "/home/***/dev/truckersmp-cli/truckersmp_cli/truckersmp.py", line 81, in update_mod
    os.makedirs(Args.moddir, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python3.9/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
~~~

Looking into it, it seems the only place where Args.prefixdir gets assigned a default value is in [configfile.py#L108](https://github.com/truckersmp-cli/truckersmp-cli/blob/main/truckersmp_cli/configfile.py#L108), which is never reached if not using a config file.

For reference, I use the following command to launch the game:
~~~
./truckersmp-cli --without-wine-discord-ipc-bridge -n <redacted> -r dx11 start ets2mp
~~~

**Comment by Lucki** [comment]
https://github.com/truckersmp-cli/truckersmp-cli/blob/ef13d5456496475e81bd362463ac7325ba9e774c/truckersmp_cli/configfile.py#L69-L70

#222

**Comment by aearil** [comment]
Thank you! And thank you for the work you put into this project!
